name: 'Hax Auto Renew'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 */1 * *'
jobs:
  hax_renew:
    runs-on: windows-2022
    steps:
      - name: 'Renewing Hax VPS ....' 
        run: |
          cmd /c curl -sSL -O https://github.com/SemiZhang/Hax_extend/raw/main/HaxAutoReNew.exe
          cmd /c HaxAutoReNew.exe -user "${{ secrets.HAX_USER }}" -password "${{ secrets.HAX_PASS }}"
